export enum QuickPickEventTypes {
  EVENT_TYPE_QUICKPICK_ORDER_READY = 259,
  EVENT_TYPE_QUICKPICK_PRINTED = 260,
  EVENT_TYPE_QUICKPICK_SCANNED = 261,
  EVENT_TYPE_QUICKPICK_DELIVER_READY = 262,
  EVENT_TYPE_QUICKPICK_OPENED = 263,
  EVENT_TYPE_QUICKPICK_BIN_REMOVED = 264,
  EVENT_TYPE_QUICKPICK_BIN_RETURNED = 265,
  EVENT_TYPE_QUICKPICK_CLOSED = 266,
  EVENT_TYPE_QUICKPICK_PROCESS_COMPLETED = 267,

  // Enable Disable Controller
  EVENT_TYPE_QUICKPICK_DISABLED = 271,
  EVENT_TYPE_QUICKPICK_ENABLED = 279,

  // Post Door open event errors
  EVENT_TYPE_QUICKPICK_BIN_NOT_REMOVED = 278,
  EVENT_TYPE_QUICKPICK_BIN_NOT_RETURNED = 276,
  EVENT_TYPE_QUICKPICK_HARDWARE_FAULTED = 275,

  // Pre Door open event errors
  EVENT_TYPE_QUICKPICK_DELIVER_TIMEOUT = 274,
  EVENT_TYPE_QUICKPICK_DELIVER_IN_PROGRESS = 272,
  EVENT_TYPE_QUICKPICK_ORDER_NOT_FOUND = 270
}
